default_platform(:ios)

platform :ios do
  desc "Upload existing IPA to TestFlight using App Store Connect API key"
  lane :ci_upload do
    app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_content: ENV['ASC_PRIVATE_KEY']
    )

    upload_to_testflight(
      ipa: "client/upload.ipa",
      skip_waiting_for_build_processing: false,
      force: true
    )
  end
end
